# Generated by Django 5.0.4 on 2024-05-02 14:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cliente_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_image),
        ),
    ]
